<?php
/**
 * CONNEXT Installer — Step 3: ติดตั้งจริง
 *  1) รัน ../db/db_setup.sql (สร้างตาราง — CREATE TABLE IF NOT EXISTS ทั้งหมด)
 *  2) seed โครงการแรก + บทบาทผู้ดูแล (level 0) + ผู้ใช้ admin
 *  3) เขียน ../settings/database.php และ ../settings/config.php
 * ทุกอย่าง idempotent — รันซ้ำได้ถ้าพลาดกลางทาง
 * PHP 7.4-compatible
 */
if (!defined('CONNEXT_INSTALLER')) { http_response_code(403); exit('Forbidden'); }

// ---- ต้องมีข้อมูลจากขั้นก่อนหน้าครบ --------------------------------------
$app = isset($_SESSION['connext_install']['app']) && is_array($_SESSION['connext_install']['app'])
    ? $_SESSION['connext_install']['app'] : null;
$db  = isset($_SESSION['connext_install']['db']) && is_array($_SESSION['connext_install']['db'])
    ? $_SESSION['connext_install']['db'] : null;

if ($app === null || empty($app['admin_username']) || !isset($app['admin_password'])) {
    inst_redirect(1);
}
if ($db === null || empty($_SESSION['connext_install']['db_ok'])) {
    inst_redirect(2);
}

// ---- SQL helpers ----------------------------------------------------------

/**
 * ตัด comment แบบ `-- ...` ออกจากบรรทัด โดยไม่แตะ `--` ที่อยู่ใน string ('...')
 * สแกนเป็น byte ได้ปลอดภัยกับ UTF-8 (ไบต์อักษรไทยไม่ชนกับ ' หรือ -)
 */
function inst_strip_line_comment($line) {
    $inStr = false;
    $len = strlen($line);
    for ($i = 0; $i < $len; $i++) {
        $ch = $line[$i];
        if ($ch === "'") {
            $inStr = !$inStr;
            continue;
        }
        if (!$inStr && $ch === '-' && ($i + 1) < $len && $line[$i + 1] === '-') {
            return substr($line, 0, $i);
        }
        if (!$inStr && $ch === '#') {
            return substr($line, 0, $i);
        }
    }
    return $line;
}

/**
 * แยกไฟล์ .sql เป็นรายคำสั่ง:
 *  1) ตัด comment `-- ...` ทิ้งก่อน (ทั้งเต็มบรรทัดและท้ายบรรทัด — ; ใน comment จึงไม่กวน)
 *  2) split ที่ ; เฉพาะนอก string
 * หมายเหตุ: ไฟล์ schema ไม่มี stored procedure/DELIMITER — ไม่ต้องรองรับ
 */
function inst_split_sql($sql) {
    // ตัด BOM
    if (strncmp($sql, "\xEF\xBB\xBF", 3) === 0) {
        $sql = substr($sql, 3);
    }
    $lines = preg_split('/\R/', $sql);
    $clean = array();
    foreach ($lines as $line) {
        $stripped = inst_strip_line_comment($line);
        if (trim($stripped) === '') { continue; }
        $clean[] = $stripped;
    }
    $joined = implode("\n", $clean);

    $stmts = array();
    $cur = '';
    $inStr = false;
    $len = strlen($joined);
    for ($i = 0; $i < $len; $i++) {
        $ch = $joined[$i];
        if ($ch === "'") {
            $inStr = !$inStr;
            $cur .= $ch;
            continue;
        }
        if ($ch === ';' && !$inStr) {
            $trimmed = trim($cur);
            if ($trimmed !== '') { $stmts[] = $trimmed; }
            $cur = '';
            continue;
        }
        $cur .= $ch;
    }
    $trimmed = trim($cur);
    if ($trimmed !== '') { $stmts[] = $trimmed; }
    return $stmts;
}

/** เขียนไฟล์ settings แบบ `<?php return array(...);` */
function inst_write_settings_file($path, array $data) {
    $php = "<?php\n"
         . "// generated by CONNEXT installer — " . date('Y-m-d H:i:s') . "\n"
         . "return " . var_export($data, true) . ";\n";
    if (file_put_contents($path, $php, LOCK_EX) === false) {
        throw new RuntimeException('เขียนไฟล์ตั้งค่าไม่สำเร็จ: ' . $path);
    }
}

// ---- ประมวลผลติดตั้ง (POST) ----------------------------------------------
$installError = '';
$log = array();

if (isset($_SERVER['REQUEST_METHOD']) && $_SERVER['REQUEST_METHOD'] === 'POST') {
    try {
        // 0) เชื่อมต่อฐานข้อมูล
        $pdo = new PDO(
            'mysql:host=' . $db['host'] . ';dbname=' . $db['dbname'] . ';charset=utf8mb4',
            $db['user'],
            $db['pass'],
            array(
                PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                PDO::ATTR_EMULATE_PREPARES   => false,
            )
        );
        $pdo->exec("SET time_zone = '+07:00'");
        $log[] = 'เชื่อมต่อฐานข้อมูล "' . $db['dbname'] . '" สำเร็จ';

        // 1) รันไฟล์ schema (CREATE TABLE IF NOT EXISTS — รันซ้ำได้)
        $sqlFile = INST_ROOT . '/db/db_setup.sql';
        if (!is_file($sqlFile) || !is_readable($sqlFile)) {
            throw new RuntimeException('ไม่พบไฟล์ db/db_setup.sql');
        }
        $raw = file_get_contents($sqlFile);
        if ($raw === false) {
            throw new RuntimeException('อ่านไฟล์ db/db_setup.sql ไม่สำเร็จ');
        }
        $stmts = inst_split_sql($raw);
        $ran = 0;
        foreach ($stmts as $stmt) {
            $pdo->exec($stmt);
            $ran++;
        }
        $log[] = 'สร้างโครงสร้างฐานข้อมูลสำเร็จ (รัน ' . $ran . ' คำสั่ง SQL)';

        // 2) seed ข้อมูลเริ่มต้น (ทำใน transaction — DDL จบไปแล้ว)
        $pdo->beginTransaction();
        try {
            // 2.1 โครงการแรก
            $st = $pdo->prepare('SELECT id FROM projects WHERE code = ?');
            $st->execute(array($app['project_code']));
            $projectId = $st->fetchColumn();
            if ($projectId === false) {
                $st = $pdo->prepare("INSERT INTO projects (code, name, status) VALUES (?, ?, 'active')");
                $st->execute(array($app['project_code'], $app['project_name']));
                $projectId = (int)$pdo->lastInsertId();
                $log[] = 'สร้างโครงการ ' . $app['project_code'] . ' — ' . $app['project_name'];
            } else {
                $projectId = (int)$projectId;
                $log[] = 'พบโครงการ ' . $app['project_code'] . ' อยู่แล้ว — ใช้ของเดิม';
            }

            // 2.2 บทบาทผู้ดูแลระบบ (level 0) — สร้างเมื่อยังไม่มี role level 0
            $roleId = $pdo->query('SELECT id FROM roles WHERE level = 0 ORDER BY id LIMIT 1')->fetchColumn();
            if ($roleId === false) {
                $st = $pdo->prepare(
                    'INSERT INTO roles (role_code, name, level, can_req, can_daily_check)
                     VALUES (?, ?, 0, 1, 1)
                     ON DUPLICATE KEY UPDATE level = 0, can_req = 1, can_daily_check = 1'
                );
                $st->execute(array('ADM', 'Administrator'));
                $st = $pdo->prepare('SELECT id FROM roles WHERE role_code = ?');
                $st->execute(array('ADM'));
                $roleId = $st->fetchColumn();
                $log[] = 'สร้างบทบาท ADM — Administrator (level 0)';
            } else {
                $log[] = 'พบบทบาทระดับผู้ดูแล (level 0) อยู่แล้ว — ใช้ของเดิม';
            }
            $roleId = (int)$roleId;

            // 2.3 ผู้ใช้ admin (bcrypt) — ถ้ามีแล้วอัปเดตรหัสผ่าน/สิทธิ์ให้ตรงตามที่กรอก
            $hash = password_hash($app['admin_password'], PASSWORD_BCRYPT);
            if ($hash === false) {
                throw new RuntimeException('สร้าง hash รหัสผ่านไม่สำเร็จ');
            }
            $st = $pdo->prepare('SELECT id FROM users WHERE username = ?');
            $st->execute(array($app['admin_username']));
            $userId = $st->fetchColumn();
            if ($userId === false) {
                $st = $pdo->prepare(
                    "INSERT INTO users (username, password, full_name, role_id, project_id, status)
                     VALUES (?, ?, ?, ?, ?, 'active')"
                );
                $st->execute(array($app['admin_username'], $hash, $app['admin_full_name'], $roleId, $projectId));
                $log[] = 'สร้างผู้ใช้ผู้ดูแลระบบ "' . $app['admin_username'] . '"';
            } else {
                $st = $pdo->prepare(
                    "UPDATE users SET password = ?, full_name = ?, role_id = ?, project_id = ?, status = 'active'
                     WHERE id = ?"
                );
                $st->execute(array($hash, $app['admin_full_name'], $roleId, $projectId, (int)$userId));
                $log[] = 'พบผู้ใช้ "' . $app['admin_username'] . '" อยู่แล้ว — อัปเดตรหัสผ่านและสิทธิ์ให้เป็นผู้ดูแล';
            }

            $pdo->commit();
        } catch (Exception $seedEx) {
            if ($pdo->inTransaction()) { $pdo->rollBack(); }
            throw $seedEx;
        }

        // 3) เขียนไฟล์ settings
        $settingsDir = INST_ROOT . '/settings';
        if (!is_dir($settingsDir)) {
            if (!mkdir($settingsDir, 0755, true)) {
                throw new RuntimeException('สร้างโฟลเดอร์ settings/ ไม่สำเร็จ');
            }
        }

        // 3.1 database.php
        inst_write_settings_file($settingsDir . '/database.php', array(
            'host'   => $db['host'],
            'dbname' => $db['dbname'],
            'user'   => $db['user'],
            'pass'   => $db['pass'],
        ));
        $log[] = 'เขียนไฟล์ settings/database.php สำเร็จ';

        // 3.2 config.php — ถ้ารันซ้ำ ให้คง gate_api_key และ installed_at เดิมไว้
        $cfgPath = $settingsDir . '/config.php';
        $old = null;
        if (is_file($cfgPath)) {
            $old = include $cfgPath;
        }
        $cfg = array(
            'app_name'     => $app['app_name'],
            'env'          => 'production',
            'installed_at' => (is_array($old) && !empty($old['installed_at']))
                                ? $old['installed_at'] : date('Y-m-d H:i:s'),
            'gate_api_key' => (is_array($old) && !empty($old['gate_api_key']))
                                ? $old['gate_api_key'] : bin2hex(random_bytes(16)),
        );
        inst_write_settings_file($cfgPath, $cfg);
        $log[] = 'เขียนไฟล์ settings/config.php สำเร็จ';

        // 4) สำเร็จ — เก็บข้อมูลสำหรับหน้าเสร็จสิ้น + ล้างรหัสผ่านออกจาก session
        $_SESSION['connext_install']['done'] = 1;
        $_SESSION['connext_install']['summary'] = array(
            'app_name'       => $app['app_name'],
            'project_code'   => $app['project_code'],
            'project_name'   => $app['project_name'],
            'admin_username' => $app['admin_username'],
        );
        unset($_SESSION['connext_install']['app']['admin_password']);
        if (isset($_SESSION['connext_install']['db']['pass'])) {
            $_SESSION['connext_install']['db']['pass'] = '';
        }
        inst_allow(4);
        inst_redirect(4);

    } catch (Exception $e) {
        $installError = $e->getMessage();
    }
}
?>
<h2>ขั้นตอนที่ 4 — ติดตั้งระบบ</h2>
<p class="sub">ตรวจสอบข้อมูลสรุปด้านล่าง แล้วกด "เริ่มติดตั้ง" — ระบบจะสร้างตาราง seed ข้อมูล และเขียนไฟล์ตั้งค่า</p>

<?php if ($installError !== ''): ?>
  <div class="alert alert-error">
    <strong>&#10007; การติดตั้งไม่สำเร็จ:</strong><br>
    <?php echo inst_e($installError); ?>
    <?php if (!empty($log)): ?>
      <br><br><strong>ขั้นตอนที่ทำสำเร็จก่อนเกิดปัญหา:</strong>
      <ul>
        <?php foreach ($log as $item): ?>
          <li><?php echo inst_e($item); ?></li>
        <?php endforeach; ?>
      </ul>
    <?php endif; ?>
    <br>สามารถกด "เริ่มติดตั้ง" ซ้ำได้ — ทุกขั้นตอนออกแบบให้รันซ้ำได้อย่างปลอดภัย (idempotent)
  </div>
<?php endif; ?>

<table class="kv">
  <tr><td class="k">ชื่อระบบ</td><td class="v"><?php echo inst_e($app['app_name']); ?></td></tr>
  <tr><td class="k">โครงการแรก</td><td class="v"><?php echo inst_e($app['project_code'] . ' — ' . $app['project_name']); ?></td></tr>
  <tr><td class="k">ผู้ดูแลระบบ</td><td class="v"><?php echo inst_e($app['admin_username'] . ' (' . $app['admin_full_name'] . ')'); ?></td></tr>
  <tr><td class="k">ฐานข้อมูล</td><td class="v"><?php echo inst_e($db['dbname'] . ' @ ' . $db['host']); ?></td></tr>
  <tr><td class="k">ผู้ใช้ฐานข้อมูล</td><td class="v"><?php echo inst_e($db['user']); ?></td></tr>
</table>

<div class="alert alert-warn" style="margin-top:14px;">
  &#9888; ระบบจะรันไฟล์ <strong>db/db_setup.sql</strong> เพื่อสร้างตารางทั้งหมด
  (ตารางที่มีอยู่แล้วจะไม่ถูกลบหรือเขียนทับ — ใช้ CREATE TABLE IF NOT EXISTS)
</div>

<form method="post" action="index.php?step=3">
  <div class="btn-row">
    <a class="btn btn-ghost" href="index.php?step=2">&larr; ย้อนกลับ</a>
    <button type="submit" class="btn right">&#9881; เริ่มติดตั้ง</button>
  </div>
</form>
